SocialSite/Accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='Accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('edit_user/<int:pk>', views.EditUser.as_view(template_name='Accounts/edit_user.html'), name='edituser'),
    path('profile/<int:pk>', views.ProfileView.as_view(template_name='Accounts/profile_page.html'),name='profileview'),
    path('profile/<int:pk>/edit', views.UpdateProfile.as_view(),name='editprof')
]  

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialSite/Groups/urls.py
#Groups URL
from django.urls import path
from . import views

app_name = 'Groups'

urlpatterns = [
    path('',views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(),name='create'),
    path('posts/in/<str:slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<str:slug>/', views.JoinGroup.as_view(),name='join'),
    path('leave/<str:slug>/', views.LeaveGroup.as_view(),name='leave'),
]

SocialSite/Posts/urls.py
from django.urls import path
from . import views

app_name = 'Posts'
#using raw literals
urlpatterns = [
    path('', views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(),name='createpost'),
    path('by/<str:username>', views.UserPosts.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>', views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(),name='delete'),
    path('post/<int:pk>/comment/', views.CreateComment.as_view(template_name="Posts/comment_form.html"), name='createcomment'),
]

SocialSite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coders</title>
    {% comment %} Bootstrap5 and theme/bundle {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% comment %} Google Fonts {% endcomment %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    
    <!-- Medium Style Editor-->
    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    
    {% comment %} CSS stylesheet {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

</head>
<body>
{% comment %} Nav bar under construction {% endcomment %}
    <nav class='navbar navbar-expand-lg navbar-dark bg-dark' role='navigation' id='navbar'>
        <div class="container-fluid">
            <a class='navbar-brand' href="{% url 'home' %}"> Learning Software Engineering </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'createpost' %}active{% endif %}" href="{% url 'Posts:createpost' %}"><span class="bi bi-pen-fill">Post</span></a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'all' %}active{% endif %}" href="{% url 'Groups:all' %}"><span class="bi bi-people-fill">Groups</span></a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'create' %}active{% endif %}" href="{% url 'Groups:create' %}"><span class="bi bi-node-plus-fill">Create Group</span></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Accounts:logout' %}"><span class="bi bi-door-closed-fill">Log Out</span></a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'edituser' %}active{% endif %}" href="{% url 'Accounts:edituser' request.user.pk %}"><span class="bi bi-gear-fill"></span></a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'profileview' %}active{% endif %}" href="{% url 'Accounts:profileview' request.user.pk %}"><span class="bi bi-person-lines-fill"></span></a></li>
                
                {% else %}
                <li class="nav-item"><a class="nav-link disabled">Post</a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'all' %}active{% endif %}" href="{% url 'Groups:all'%}"><span class="bi bi-people-fill">Groups</span></a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'Accounts:login'%}"><span class="bi bi-door-open-fill">Log In<span></a></li>
                <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'signup' %}active{% endif %}" href="{% url 'Accounts:signup'%}"><span class="bi bi-person-plus-fill">Sign Up</span></a></li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'search' %}" method="GET">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name='search'>
                <button class="btn btn-outline-light" type="submit"><span class="bi bi-search"></span></button>
            </form>
        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
<div class='container'>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
<div class="col-md-4 d-flex align-items-center"><span>Derek's Site</span></div>
<ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
    <li class="ms-3"><a href="https://github.com/DLiSWE"><img src="{% static 'images/github_logo.jpg' %}"/></a></li>
    <li class="ms-3"><a href="#"><i class="bi bi-envelope-open-fill" style="font-size:23px;color:white;"></a></i></span></li>
</footer>
</div>

</html>

SocialSite/templates/index.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
<h1>Hello</h1>
<figure class="text-end">
    <blockquote class="blockquote">
      <p>Welcome! Sign up and Join any group you like, and if there aren't any, you
          can make your own! Start up a conversation with others here.
      </p>
    </blockquote>
    <figcaption class="blockquote-footer">
      Abraham Lincoln or something
    </figcaption>
  </figure>
{% endblock %}
</body>
</html>

SocialSite/templates/search_for.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block content%}
<div>
<h1> Search </h1>
{% for message in object_list %}
<div class="border-top">
<h4>
    {{ message|linebreaksbr|safe }},
    {% comment %} {{ message_html }} {% endcomment %}
</h4>
<br>
</div>
{%endfor%}
</div>

{% endblock %}

SocialSite/templates/test.html
{% extends "base.html" %}
{% load static %} 
{%block content %}
<h1>You are now logged in</h1>
{% endblock%}

SocialSite/templates/thanks.html
{% extends "base.html" %}
{% load static %} 
{%block content %}
<h1>Thanks for visiting! Come back again.</h1>
{% endblock%}