SocialSite/Groups/urls.py
#Groups URL
from django.urls import path
from . import views

app_name = 'Groups'

urlpatterns = [
    path('',views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(),name='create'),
    path('posts/in/<str:slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<str:slug>/', views.JoinGroup.as_view(),name='join'),
    path('leave/<str:slug>/', views.LeaveGroup.as_view(),name='leave'),
]

SocialSite/Groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse

#get current user
User = get_user_model()
#load custom templates
register = template.Library()

class Group(models.Model):
    """
    Group Model
    Attributes:
    Name: Character Field, unique has to be true because why have 2 groups with the same name
    Description: Text, description of the group's purpose
    Description_html: Uses Misaka module to allow html tags to do it's join in description
    Members: Many to many field with users that are considered Group Members
    """
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='Enter Text Here')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name
    
    #save slugified html link and description
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    #get html url link using reverse on posts and the slugified html link
    def get_absolute_url(self):
        return reverse('Groups:single',kwargs={'slug':self.slug})

    #order
    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    """
    Group Member Model: Models to create relationships of users by groups
    Attributes:
    Group: Foreign key with Group model in Group App on related name of membership
    User: Foreign key with current User/ User=get_user_model
    """
    group = models.ForeignKey(Group, related_name='memberships', on_delete = models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups', on_delete = models.CASCADE)

    #return username if str representation if needed
    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

SocialSite/Groups/forms.py
from django import forms

from Posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                pk__in=user.groups.values_list("Groups__pk")
                )
            )

SocialSite/Groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.shortcuts import get_object_or_404
from Groups.models import Group, GroupMember
from Posts.models import Post
from braces.views import SelectRelatedMixin
from . import models

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('Groups:single', kwargs={'slug':self.kwargs.get('slug')})

#create query to assign user to group/one to many relationship
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        #specify if groupmember is already in group
        except:
            messages.warning(self.request,'Already a member!')
        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('Groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Whoops, you are not a member')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')
        
        return super().get(request,*args,**kwargs)

SocialSite/Groups/templates/groups/group_detail.html
{% extends "Groups/groups_base.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count: {{ group.members.count }}</h2>
<div class="content">
    <div class="row">
        {% if user in group.members.all %}
            <a href="{% url 'Groups:leave' slug=group.slug %}"
            class = 'btn btn-lg btn-fill btn-warning'>
            <span class="bi bi-door-open-fill">Leave<span></a>
        {% else %}
            <a href="{% url 'Groups:join' slug=group.slug %}"
            class = "btn btn-lg btn-fill btn-primary"><span
            class = "bi bi-person-plus-fill"></span>Join</a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %} 
    <div class = "col-md-8">
    {% if group.postin.count == 0 %}
        <h2> No posts available yet! Start a conversation here! </h2>
    {% else %}
        {% for post in group.postin.all %}
        {% include "Posts/_post.html" %}
        <br>
        {% for comment in post.comments.all %}
        {% include "Posts/_comments.html" %}
        {% endfor %}
        {% endfor %}
        
    {% endif %}    
    
</div>
      
</div>
{% endblock %}

SocialSite/Groups/templates/groups/group_form.html
{% extends "Groups/groups_base.html "%}
{% load static %} 
{% load bootstrap5 %}

{% block group_content %}
<h4> Create a new group!</h4>

<form action="{% url 'Groups:create' %}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-fill btn-info me-2" value="Create">
</form>

{% endblock %}

SocialSite/Groups/templates/groups/group_list.html
{% extends "Groups/groups_base.html" %}
{% load static %} 
{% block pregroup %}
<div class="col-md-4">
    <div class = "content">
    {% if user.is_authenticated %}
    <h2>Welcome Back!</h2>
<a href="{% url 'Posts:for_user' username=user.username%}">
    <div class = "card profile">
        <a href="{% url 'Posts:for_user' username=user.username%}">
            <img class="card-img-top" src="{{user.avatar.url}}">
            <p class="card-text">@{{user.username}}</p>
  
    </div>    
</a>
    {% endif %}
    
    <h2> Groups </h2>
    <p> Welcome to the groups page!</p>
</div>
    {% if user.is_authenticated %}
    <a href ="{% url 'Groups:create' %}" class = 'btn btn-md btn-fill btn-info'>
        <span class="bi bi-clipboard-plus">Create New Group</span></a>
    {%endif%}

</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a class='list-group-item list-group-item-action bg-black text-white border' href="{% url 'Groups:single' slug=group.slug %}">
            <h3 class='title list-group-item-heading'>{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {% comment %} Using pipe will allow user text to look like what its supposed to{% endcomment %}
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class='badge rounded-pill bg-danger'>{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class='badge rounded-pill bg-danger'>{{group.postin.count}}</span>
                        post{{group.postin.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
</div>

{% endblock %}

SocialSite/Groups/templates/groups/groups_base.html
{% extends "base.html" %}
{% load static %} 

{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %} {%endblock%}
        {% block group_content %} {%endblock%}
        {% block postgroup %} {%endblock%}
    </div>
</div>

{% endblock %}

SocialSite/Groups/templates/groups/groups_detail.html
{% extends "Groups/group_base.html" %}
{% block pregroup %}

<h1>{{group.name}}</h1>
<h2>Member Count: {{Groups.members.count }}</h2>
<div class="content">
    <div class="row">

        {% if user in Groups.members.all %}
            <a href="{url 'Groups:leave' slug=group.slug %}"
            class = 'btn btn-lg btn-fill btn-warning'>
            <span class='glyphicon glyphicon-remove-circle'>Leave<span></a>
        {% else %}
        <a href="{% url 'Groups:join' slug=group.slug %}"
        class = "btn btn-lg btn-fill btn-warning"><span
        class = "glyphicon glyphicon-ok-circle"></span>Leave</a>
        {% endif %}

</div>

        {% endblock %}
    {% block group_content %} 
        <div class = "col-md-8">
    {% if group.posts.count == 0 %}
        <h2> No posts available yet! </h2>
    {% else %}
        {% for post in group.posts.all %}
        {% comment %} inject posts/_post.html using include here {% endcomment %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {% endif %}

</div>

{% endblock %}

SocialSite/Groups/templates/groups/groups_list.html
{% extends Groups/group_base.html %}

{% block pregroup %}
<div class="col-md-4">
    <div class = "content">
    {% if user.is_authenticated %}
    <h2>Welcome Back!
        <a href="{% url 'Posts:for_user' username=user.username%}">
            @{{user.username}}
        </a>
    </h2>
    
    {% endif %}

    <h2> Groups </h2>
    <p> Welcome to the groups page!</p>

</div>
    {% if user.is_authenticated %}
    <a href ="{% url 'Groups:create' %}" class = 'btn btn-md btn-fill btn-warning'>
        <span class='glyphicon glyphicon-plus-sign'>Create New Group</span>
    
    </a>

{%endif%}
</div>
{% endblock %}

{% block group_content%}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a class='list-group-item' href="{% url 'Groups:single' slug=group.slug %}">
            <h3 class='title list-group-item-heading'>{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {% comment %} Using pipe will allow user text to look like what its supposed to{% endcomment %}
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class='badge'>{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class='badge'>{{group.posts.count}}</span>
                        post{{group.posts.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
</div>

SocialSite/Groups/templates/groups/groups_newform.html
{% extends "Groups/group_base.html "%}
{% load botstrap5 %}

{% block group_content %}
<h4> Create a new group!</h4>

<form action="{% url 'Groups:create'%}" method="post" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>

{% endblock %}