SocialSite/Accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='Accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('edit_user/<int:pk>', views.EditUser.as_view(template_name='Accounts/edit_user.html'), name='edituser'),
    path('profile/<int:pk>', views.ProfileView.as_view(template_name='Accounts/profile_page.html'),name='profileview'),
    path('profile/<int:pk>/edit', views.UpdateProfile.as_view(),name='editprof')
]  

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialSite/Accounts/models.py
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from PIL import Image

# Create your models here.
class EndUser(AbstractUser,PermissionsMixin):
    #username, email, password1,password2
    #return username with @ for social media "aesthetics"
    urls = models.URLField(blank=True,null=True)
    avatar = models.ImageField(default='default_profile.jpg', upload_to='media/profile_pics/')
    bio = models.TextField(blank=True,null=True)


    def __str__(self):
        return str(self.username)

    def save(self, *args, **kwargs):
        super(EndUser,self).save(*args,**kwargs)
        img = Image.open(self.avatar.path) # Open image
    # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.avatar.path) # Save it again and override the larger image

SocialSite/Accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import EndUser
from django.conf import settings


class UserForm(UserCreationForm):
    class Meta:
        fields = ('username','email', 'password1', 'password2')
        model = get_user_model()

class SignupForm(UserForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'
    
class EditForm(UserForm):
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Change Username'
        self.fields['email'].label = 'Change Email Address'

class ProfileUpdateForm(UserForm):
    avatar = forms.ImageField()
    urls = forms.URLField()
    bio = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ['avatar','urls','bio']

    def clean_photo(self):
        photo=self.cleaned_data.get('avatar')
        if photo.size>settings.MAX_UPLOAD_SIZE:
            raise forms.ValidationError(("{}".format(str(settings.MAX_UPLOAD_SIZE/1000000))))
        return photo
        

SocialSite/Accounts/views.py
from profile import Profile
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from .forms import SignupForm, EditForm, ProfileUpdateForm
from django.contrib.auth import get_user_model


# Create your views here.
#
class SignUp(CreateView):
    model = get_user_model()
    form_class = SignupForm
    #we use reverse lazy over here instead of lazy because we don't want to
    #execute before signing up
    template_name = 'Accounts/signup.html'
    success_url = reverse_lazy('login')

class EditUser(UpdateView, LoginRequiredMixin):
    model = get_user_model()
    #temporary form
    form_class = EditForm
    template_name = 'Accounts/edit_user.html'
    success_url = reverse_lazy('Groups:all')


class UpdateProfile(UpdateView, LoginRequiredMixin):
    model = get_user_model()
    form_class = ProfileUpdateForm
    template_name = 'Accounts/edit_profile.html'
    success_url = reverse_lazy('Groups:all')
    #TODO:Logs out after updating profile...can i fix this?

class ProfileView(DetailView):
    model = get_user_model()
    template_name = 'Accounts/profile_page.html'
    

SocialSite/Accounts/templates/accounts/edit_profile.html
{% extends "Accounts/profile_page.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block content %}
<div class="col-4">
<div class = "card profile">
        <img class="card-img-top" src="{{user.avatar.url}}">
        <p class="card-text">@{{user.username}}</p>
        <p class="card-text">{{user.bio}}</p>
</div>
</div>   
<div class = "container">
    <h2>Edit</h2>
    <p style="color:red"><strong><i>Changing your profile will log out you</i></strong></p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" value="Change">
    </form>
</div>
{% endblock %}

SocialSite/Accounts/templates/accounts/edit_user.html
{% extends "Accounts/profile_base.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block pcontent %}
<div class = "container">
    <h1>Account Settings</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" value="Edit">
    </form>
</div>
{% endblock %}

SocialSite/Accounts/templates/accounts/login.html
{% extends "Accounts/profile_base.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block pcontent %}
<div class = "container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" value="Login">
    </form>
</div>
{% endblock %}

SocialSite/Accounts/templates/accounts/profile_base.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
<div class="profile-page">
    <div class="container">
        <div class="row text-center">
            {% block pcontent %}{% endblock %}
            {% block profile_content %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

SocialSite/Accounts/templates/accounts/profile_page.html
{% extends "Accounts/profile_base.html" %}
{% load static %} 

{% block pcontent %}
<div class = "col-md-4">
    <h1>{{ user.username }}</h1>
    <img class="rounded-circle account-img" src={{ user.avatar.url }}>
    <h6><a href="{{user.urls}}">{{ user.urls }}</a></h6>
    <p class='text-start'>{{ user.bio }}</p>
<button class='btn btn-info'><a href="{% url 'Accounts:editprof' request.user.pk %}">Edit Profile</a></button>
</div>
{% comment %} posts/_post.html {% endcomment %}
{% endblock %}

{% block profile_content %}
    <div class="col-md-8">
        <div class="list-group">
            <p>In Groups:</p>
            {% for membergroup in object.user_groups.all %}
            <a class='list-group-item list-group-item-action bg-black text-white border' href="{% url 'Groups:single' membergroup.group.slug %}">
                <h3 class='title list-group-item-heading'>{{membergroup.group.name}}</h3>
                <div class="list-group-item-text container-fluid">
                    {% comment %} Using pipe will allow user text to look like what its supposed to{% endcomment %}
                    <div class="row">
                        <div class="col-md-4">
                            <span class='badge rounded-pill bg-danger'>{{membergroup.group.members.count}}</span>
                            member{{group.members.count|pluralize}}
                        </div>
                        <div class="col-md-4">
                            <span class='badge rounded-pill bg-danger'>{{membergroup.group.postin.count}}</span>
                            post{{group.postin.count|pluralize}}
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
        </div>
    </div>
    <div class="col-md-8 ms-auto">
        <div class="list-group">
            <p> Posts </p>
            {% for inpost in object.postin.all %}
            <p>{{ inpost }}</p>
            {% comment %} {% include "Posts/_post.html" %} {% endcomment %}
        {% endfor %}
        </div>
    </div>
{% endblock %}

SocialSite/Accounts/templates/accounts/signup.html
{% extends "Accounts/profile_base.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block pcontent %}
<div class = "container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Sign Up">
    </form>   
</div>
{% endblock %}