SocialSite/Posts/urls.py
from django.urls import path
from . import views

app_name = 'Posts'
#using raw literals
urlpatterns = [
    path('', views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(),name='createpost'),
    path('by/<str:username>', views.UserPosts.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>', views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(),name='delete'),
    path('post/<int:pk>/comment/', views.CreateComment.as_view(template_name="Posts/comment_form.html"), name='createcomment'),
]

SocialSite/Posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from Groups.models import Group, GroupMember
from django.contrib.auth import get_user_model

# Create your models here.
#Get current user session
User = get_user_model()

class Post(models.Model):
    """
    Class: Post model
    Attributes:
    User: Foreign key associated with User model that is initialized by get_user_model()
    Date Created: Date time field with current time as input
    Message: User text field description
    Message HTML: markdown safe text description of Message attribute
    Group: Foreign key associated with Group model, imported from Groups app
    """
    user = models.ForeignKey(User,related_name='poster', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='postin',null=True,blank=True, on_delete = models.CASCADE)

    #return stringified msg
    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        #misaka here allows messages with html, etc. to display correctly
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)    

    #This will create the url link for the post. 
    def get_absolute_url(self):
        return reverse("Posts:single", kwargs={"username":self.user.username,
                                                "pk": self.pk})
    
    class Meta:
        #descending order of created at value
        ordering = ['-created_at']
        #every message is linked to a unique user
        unique_together = ['user', 'message']

class Comment(models.Model):
    """
    Class: Comment model
    Attributes:
    Post" Foreign key associated with Post PK
    User: Foreign key associated with User model that is initialized by get_user_model()
    Date Created: Date time field with current time as input
    Message: User text field description
    Message HTML: markdown safe text description of Message attribute
    Group: Foreign key associated with Group model, imported from Groups app
    """
    post = models.ForeignKey(Post, related_name='comments', null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='commenter', null=True, blank=True, on_delete=models.CASCADE)
    message_html = models.TextField(editable=False, null=True, blank=True)
    message = models.TextField()
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message    

    def save(self,*args,**kwargs):
        #misaka here allows messages with html, etc. to display correctly
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)    

    def get_absolute_url(self):
        return reverse('post_list', kwargs={"username":self.user.username,
                                                "pk": self.pk})

    class Meta:
        #descending order of created at value
        ordering = ['-create_date']

SocialSite/Posts/views.py
from django.db.models import query
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.views import generic
from django.contrib.auth import get_user_model
from braces.views import SelectRelatedMixin
from django.contrib import messages
from . import models
from .form_post import CommentForm



# Create your views here.
User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'Posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('poster').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.poster.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):

    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):

    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('Posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

##############################

class CreateComment(LoginRequiredMixin, generic.CreateView):
    form_class= CommentForm
    model = models.Comment
    success_url = reverse_lazy('Groups:all')

    # def get_success_url(self):
    #     url_slug = self.kwargs['slug']
    #     return reverse_lazy('Groups', kwargs={'slug': url_slug})

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        post_id = self.kwargs['pk']
        post = models.Post.objects.get(pk=post_id)  
        self.object.post = post
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        print('form invalid')
        print(form.errors.values())
        return render(form, 'Posts/comment_form.html', {'form':form})

#Maybe Later?
    # def get_form(self, form_class=None):
    #     form = super(CreateComment, self).get_form(form_class)
    #     post_id = self.kwargs['pk']
    #     post = models.Post.objects.get(pk=post_id)       
    #     return CommentForm(initial={'post':post})
        

SocialSite/Posts/templates/posts/_comments.html
<div class="card text-black bg-secondary text-center">
    <h6>{{comment.message_html|safe|linebreaks}}</h6>
    <div class="card-body text-black bg-secondary">
        <img class="rounded-circle account-img" src="{{ post.user.avatar.url }}" width="20" height="20">
    <span class='username'>
        <a href="{% url 'Posts:for_user' username=comment.user.username %}">@{{comment.user.username}}</a>
    </span>
    <time class='time'>
        <p>{{ comment.create_date }}</p>
    </time>
</div>
</div>

SocialSite/Posts/templates/posts/_post.html
{% comment %} inject content in templates {% endcomment %}
<br>
<div class="post media border" style="padding: 20px">
    <h4>{{post.message_html|safe|linebreaks}}</h4>
    
    <div class="media-body">
        <img class="rounded-circle account-img" src="{{ post.user.avatar.url }}" width="35" height="35">
        <strong>{{post.user.username}}</strong>
        <h5 class='media-heading'>
        <span class='username'>
            <a href="{% url 'Posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
        </span>
        <time class='time'>
            <a href="{% url 'Posts:single' username=post.user.username pk=post.pk%}">{{ post.created_at }}</a>
        </time>
        {% if post.group %}
        <span class="group-name"> in {{ post.group.name }}</span>
        {% endif %}
        </h5>
    <br>
        <div class="media-footer">
            {% if user.is_authenticated and post.user == user %}
                <a href="{% url 'Posts:delete' pk=post.pk %}" title="delete"
                class='btn btn-md btn-fill btn-danger'>
                {% comment %} aria tells screen readers to not read html tags outloud. For disabled {% endcomment %}
                    <span class='bi bi-bookmark-x-fill'> Delete</span>
                </a>
                {% endif %}
                {% comment %} {% url 'Posts:comment' %} {% endcomment %}
            <a href="{% url 'Posts:createcomment' pk=post.pk %}" title="comment" class='btn btn-md btn-fill btn-info'>
                <span class='bi bi-bookmark-plus-fill'>Comment</span>
            </a>
        </div>
    
    </div>
</div>

SocialSite/Posts/templates/posts/comment_form.html
{% extends "Posts/post_base.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block post_comment %}
<h1>New Comment</h1>
<form id="commentForm" action="{% url 'Posts:createcomment' view.kwargs.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} <input type="hidden" value="{{post.pk}}" name="post_id"> {% endcomment %}
    <input type="submit" value="Post" class="btn btn-info">
</form>
<script> var editor = new MediumEditor('.editable');
</script>
{% endblock %}

SocialSite/Posts/templates/posts/post_base.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_comment %} {% endblock %}
            {% block post_post %}{% endblock %}

        </div>
    </div>
</div>
{% endblock %}

SocialSite/Posts/templates/posts/post_confirm_delete.html
{% extends "Posts/post_base.html" %}
{% load static %} 

{% block post_content %}
<h3> Are you sure you want to delete this post?</h3>

<div class="posts">
    {% include "Posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class='btn btn-danger btn-large'>
    <a href="{% url 'Posts:single' username=user.username pk=object.pk %}"
    class='btn btn-simple btn-large btn-default'>Cancel</a>
</form>

{% endblock %}

SocialSite/Posts/templates/posts/post_detail.html
{% extends "Posts/post_base.html" %}
{% load static %} 

{% block post_content %}

<div class="col-md-8">
    {% include "Posts/_post.html" %}
    
</div>

{% endblock %}

SocialSite/Posts/templates/posts/post_form.html
{% extends "Posts/post_base.html" %}
{% load static %} 
{% load bootstrap5 %}

{% block post_content %}
<h4>Create a new Post</h4>
<form id='postForm' action="{% url 'Posts:createpost' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class='btn btn-info me-3'>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

SocialSite/Posts/templates/posts/post_list.html
{% extends 'Posts/post_base.html' %}
{% load static %} 

{% block pre_post_content %}
{% comment %} post_list {% endcomment %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="stroke" data-text="Gradient stroke">
            <h4 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {% for member_group in get_user_groups %}
                <li class = 'group li-with-bullet'>
                    <a href="{% url 'Groups:single' slug=member_group.group.slug %}"></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    {% endif %}
    <div class="card card-with-showdow">
        <div class="content">
            <h5 class='title'>All Groups</h5>
            <ul class='list-unstyled'>
                {% for other_group in get_other_groups %}
                <li class = 'group li-with-bullet'>
                    <a href="{% url 'Groups:single' slug=other_group.slug %}"></a>
                </li>
                {%endfor%}
            </ul>    
        </div>
    </div>
</div>

{%endblock%}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
        {% include "Posts/_post.html" %}
    {% endfor %}
{% endblock %}

SocialSite/Posts/templates/posts/user_post_list.html
{% extends "Posts/post_base.html" %}
{% load static %} 
{% block prepost %}
    <div class="col-md-4">
        <h1>@{{post_user.username}}</h1>
        <img src="{{ post_user.avatar.url }}">
    </div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
    {% include "Posts/_post.html" %}
    {% endfor %}
</div>

{% endblock %}